[tool.streamlit]
python_version = "3.10"

[theme]
primaryColor = "#228B22"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#E9ECEF"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
